server {
    listen 80;
    server_name ai-analyzer.local;

    root /var/www/public;
    index index.php;

    location / {
        try_files $uri $uri/ /index.php?$query_string;
    }

    location ~ \.php$ {
        include fastcgi_params;
        fastcgi_pass ai-analyzer_app:9000;
        fastcgi_index index.php;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;

        fastcgi_param HTTP_X_FORWARDED_FOR   $proxy_add_x_forwarded_for;
        fastcgi_param HTTP_X_FORWARDED_PROTO $scheme;
        fastcgi_param HTTP_X_FORWARDED_HOST  $http_host;
        fastcgi_param HTTP_X_FORWARDED_PORT  $server_port;
        fastcgi_param HTTP_CF_CONNECTING_IP  $http_cf_connecting_ip;

        fastcgi_connect_timeout 600;
        fastcgi_send_timeout 600;
        fastcgi_read_timeout 600;
        send_timeout 600;
    }

    location ~* \.(jpg|jpeg|gif|png|webp|svg|woff|woff2|ttf|css|js|ico|xml)$ {
        access_log off;
        log_not_found off;
        expires 360d;
        add_header Cache-Control "public, max-age=31104000, immutable";
    }

    location ~ /\.ht {
        deny all;
    }
}
